version: "3.8"

services:
  # Define the Flask app service
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=db
      - DB_USER=crypto_user
      - DB_PASSWORD=crypto_pass
      - DB_NAME=crypto_db
    depends_on:
      - db

  # Define the PostgreSQL service
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: